### PR TITLE
Adding task to recover terminal resources on founding new room

### PR DESCRIPTION
**Pull request by MatthewARoy**
### Description:
Doesn't destroy terminal if there are resources left and creates a haul directive under it.

Untested because my test room leveled up with wrong branch active 😬

### CODE REVIEW

**Comment by bencbartlett** [comment]
This looks good, but I'm not confident enough in `HaulerOverlord` to want to merge this just yet -- have you tested their behavior yet? It's been a while since I've last played with them.

**Comment by MatthewARoy** [comment]
@bencbartlett Hauling works ok, it's got some bugs but it's better than nothing. It terminates too early right now.

**Comment by bencbartlett** [comment]
This does seem like a good feature to add, but looking at it a second time, I'd rather it be done slightly differently. Let's destroy unowned terminal at RCL6 (separate from storage at RCL4) in room planner, and have the overseer create a haul directive once the colony has an owned storage up. (Currently it seems like hauling would create a haul directive immediately, even before you have a place to put all the resources in the terminal).

**Review by bencbartlett — CHANGES_REQUESTED** [review]
This does seem like a good feature to add, but looking at it a second time, I'd rather it be done slightly differently. Let's destroy unowned terminal at RCL6 (separate from storage at RCL4) in room planner, and have the overseer create a haul directive once the colony has an owned storage up. (Currently it seems like hauling would create a haul directive immediately, even before you have a place to put all the resources in the terminal).

**Comment by MatthewARoy** [comment]
@bencbartlett What do you think about just making it an else if?
That way it'll trigger at RCL 5, and you can collect the storage contents when you've had some time to settle down after making storage. I'll push to show you what I mean.

**Comment by MatthewARoy** [comment]
Second thought: What if we just make it a check that happens at RCL 5? That way it happens once, and the room will have settled down from just making storage, an energy intensive operation.

**Pull request closed without merging**
