### PR TITLE
Add basic support for enemy PowerCreeps.

### PR DESCRIPTION
**Pull request by ahmedcharles**
I haven't tested it since I'm not running Overmind on MMO. There's also no attempt to accurately reflect the 'danger' of a hostile power creep relative to other creeps, since I have no idea how that should work.

### CODE REVIEW

**Comment by bencbartlett** [comment]
This looks good upon first inspection, but please test any pull requests on MMO or private server. I can test this later myself once I get time to work on Screeps again, but it should be tested before it is merged.

Also, on another note, why do you force-push all of your commits in the pull requests?

**Comment by ahmedcharles** [comment]
I rebase them on top of the latest master commit so that they mostly result in a linear history rather than one with lots of tangled branches. I use `git log --graph` (well and other options with it) a lot and linear histories are easier to reason about.

**Comment by ahmedcharles** [comment]
Oh, and on the testing, I started running this on S+, that's how I found the issues. It's harder to test what happens with enemy power creeps since I can't force some to come over.

**Comment by bencbartlett** [comment]
I haven't forgotten about this; the `typed-screeps` repo just merged support for PowerCreeps, so we can probably expect an updated npm release soon. I'll revisit this once that happens!

**Comment by ahmedcharles** [comment]
Updated to the new typed-screeps release.

**Pull request closed without merging**
