### PR TITLE
Add visuals for intel.

### PR DESCRIPTION
**Pull request by ahmedcharles**
I like the existing visuals and I'd like to have some way of knowing what the expansion planner thinks of various rooms. This isn't the best (prettiest) implementation but it's not entirely obvious to me how to get it to do the boxes, etc. Any recommendations/thoughts?

### CODE REVIEW

**Comment by bencbartlett** [comment]
I would also like to add more visuals to intel, but drawing the inhabitability of every room on every tick is both expensive and cluttered, so I won't merge this as-is, but I'll keep the PR open if you'd like to continue to iterate on it, or until I come up with a more permanent solution. When I do another pass at the visuals sometime in the near future I'll try to improve the visuals some.

In the nearer future, I'll try to add console methods to get the expansionPlanner's possible expansion choices and to allow you to manually pre-select rooms to settle in.

**Comment by ahmedcharles** [comment]
I was thinking of adding a mode where intel is shown that's off by default. Do you mind pointing out which code does the boxes? It'd be nice to place the optional intel in a box in the upper right.

**Comment by bencbartlett** [comment]
All high-level visualization code is in the [visualizer](https://github.com/bencbartlett/Overmind/blob/master/src/visuals/Visualizer.ts), and some lower-level drawing code is in the [RoomVisual prototypes](https://github.com/bencbartlett/Overmind/blob/master/src/prototypes/RoomVisual.ts). If you're looking for something like the notifications box, use `Visualizer.infoBox`. (Which is separate from the confusingly identically-named RoomVisual.infoBox 😬 )

**Comment by ahmedcharles** [comment]
I made them optional and off by default. Is this good enough for now? (Note: `visuals()` still needs to be called from `Overmind.visuals()`.)

**Pull request closed without merging**
