### PR TITLE
Make the default mode Manual.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by semperrabbit** [comment]
This is a great idea, although it would prevent Overmind from being used as a bot on a private server. Perhaps add a name check for a suffix of `Bot` or check shard names before deciding to go auto vs manual...
That being said, I'm definitely in favor of anyone new using Overmind on MMO as an NCP being manual by default.

**Comment by Coolfeather2** [comment]
I don't see this changing anything? People will just change the mode?

**Comment by semperrabbit** [comment]
Even if it helps with a few NCPs who don't know how to switch modes, it's a net positive in my books.

**Comment by ahmedcharles** [comment]
Figuring out how to change the mode is one step in the right direction, IMO.

**Comment by ahmedcharles** [comment]
Changed it to use `onPublicServer()` just like the other setting below it.

**Comment by bencbartlett** [comment]
I do plan on making Overmind more tame/manageable on the public servers, and thank you for this pull request, but I don't think this is the best way to go about doing it, for a few reasons:

1. The "operation mode" mechanic was intended only as a temporary holdover until I develop more advanced logic for when to claim and (primarily) when to unclaim rooms.
2. I haven't tested manual operation in ages, since I run on `semiautomatic` and `automatic`, so there are likely many bugs which I would need to address.
3. Running the bot on manual involves doing a lot of tedious things that aren't immediately obvious how to do, like operating the room planner.
4. As @Coolfeather2 pointed out, all players have to do is to type `help` to see how to change the operating mode.

**Comment by ahmedcharles** [comment]
1. What if I offer to maintain it? (That's the only counter I can think of to "I don't want this feature long term.")
2. What if I respawn in S+ and test it?
3. I'm pretty sure that spawning as a newbie in screeps is tedious without Overmind. Only having to place flags/construction sites and read code that does stuff is way less tedious than actually having to write the code. I.e. making it tedious is the point, right (ignoring the fact that tedious is subjective and different for each person)?
4. Sure, but at that point, they're engaging. Part of the reason I proposed this is to observe how many people even do this much engagement.

Granted, I think 'semiautomatic' would be fine except that it selects outposts and defends them. If there were a mode that constrained itself to a single room and only does automated stuff in that room, I'd go for it. I'm even willing to submit changes to add such a mode, if those would be accepted.

**Comment by Coolfeather2** [comment]
I like the idea of your fourth 'default' mode, in which overmind controls one room fully automatically -  and also if we state somewhere in the readme mode about this mode and it being the default selected?

Even if Muon is to write a new system to handle states, this should be a good temporary solution

**Pull request closed without merging**
