### PR TITLE
Ensure that new colonies have accurate intel.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by bencbartlett** [comment]
Can you explain the purpose of these changes? I don't like having a directive modify the room planner or room intel settings. Modules should be as separated as possible to makes the code cleaner, more understandable, and easier to debug.

**Comment by ahmedcharles** [comment]
If you place a colonize flag somewhere that has 'bad' intel (I'm not sure how it became bad), then it will colonize the room but not select a location for the base, since it thinks the room isn't inhabitable.

I'm fine with modules being separate (it's a good design goal). If you let me know how you'd prefer this to be communicated/accomplished, I'll change it to work that way and test it again.

**Comment by bencbartlett** [comment]
Sorry, I still don't understand the purpose of these changes. Finalizing the room planner when a colonizing room becomes claimed will break operation on manual/semiautomatic mode. I'm also not sure what you mean by how the intel "becomes bad" -- if you've found a bug in the expansion planner, please let me know and I'll try to fix it! But this seems like adding some changes for a problem which I'm not sure exists.

**Comment by ahmedcharles** [comment]
Ok, so this fixes the expansion data bug without changing the room planner behavior. (Note, I don't know how this situation happens, I just know that I experienced it.)

As an aside, the change I removed, which was to finalize the planner was intended to allow placing a flag and having it automatically pick the location within the room to build the bunker. That's a design change and not a bug fix, though I'm not entirely sure why it would 'break', unless by break, you simply mean that it would not allow a manual choice of location.

**Pull request closed without merging**
